# Generated by Django 3.1.1 on 2021-07-14 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0007_auto_20210526_1529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='enviador',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_proyecto', to='panel_carga.proyecto'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha envio'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='visto'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Umbral'), (2, 'Transmittal'), (3, 'Tarea')], verbose_name='tipo notificación'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='text_preview',
            field=models.CharField(blank=True, max_length=90, verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
