# Generated by Django 3.1.1 on 2021-01-28 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel_carga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('status', models.BooleanField(blank=True, default=0, verbose_name='Status')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrevPaquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('prev_fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('prev_asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('prev_descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('prev_status', models.BooleanField(blank=True, default=0, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Versión')),
                ('comentario', models.FileField(blank=True, upload_to='proyecto/comentarios/')),
                ('archivo', models.FileField(blank=True, upload_to='proyecto/documentos/')),
                ('revision', models.IntegerField(choices=[('', '------'), (1, 'Revision B'), (2, 'Revision C'), (3, 'Revision D'), (4, 'Revision E'), (5, 'Revision 0'), (6, 'Revision 1'), (7, 'Revision 2'), (8, 'Revision 3'), (9, 'Revision 4'), (10, 'Revision 5')], verbose_name='Revisión')),
                ('estado_cliente', models.IntegerField(blank=True, choices=[('', '------'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Válido para construcción'), (6, 'Mantener Revisión')], default=1)),
                ('estado_contratista', models.IntegerField(blank=True, choices=[('', '------'), (1, 'Para revisión'), (2, 'Para aprobación')], default=1)),
                ('valido', models.BooleanField(default=1, verbose_name='Válido')),
                ('documento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
        ),
        migrations.CreateModel(
            name='PrevVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Version')),
                ('prev_comentario', models.FileField(blank=True, upload_to='proyecto/comentarios/')),
                ('prev_archivo', models.FileField(blank=True, upload_to='proyecto/documentos/')),
                ('prev_revision', models.IntegerField(choices=[('', '------'), (1, 'Revision B'), (2, 'Revision C'), (3, 'Revision D'), (4, 'Revision E'), (5, 'Revision 0'), (6, 'Revision 1'), (7, 'Revision 2'), (8, 'Revision 3'), (9, 'Revision 4'), (10, 'Revision 5')], verbose_name='Revisión')),
                ('prev_estado_cliente', models.IntegerField(blank=True, choices=[('', '------'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Válido para construcción'), (6, 'Mantener Revisión')], null=True)),
                ('prev_estado_contratista', models.IntegerField(blank=True, choices=[('', '------'), (1, 'Para revisión'), (2, 'Para aprobación')], null=True)),
                ('prev_valido', models.BooleanField(default=1, verbose_name='Valido')),
                ('prev_documento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento')),
                ('prev_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
        ),
        migrations.CreateModel(
            name='PrevPaqueteDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('prev_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.prevpaquete')),
                ('prev_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.prevversion')),
            ],
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_documento',
            field=models.ManyToManyField(through='bandeja_es.PrevPaqueteDocumento', to='bandeja_es.PrevVersion'),
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevpropietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevdestinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaqueteDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.paquete')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.version')),
            ],
        ),
        migrations.AddField(
            model_name='paquete',
            name='version',
            field=models.ManyToManyField(through='bandeja_es.PaqueteDocumento', to='bandeja_es.Version'),
        ),
        migrations.CreateModel(
            name='BorradorPaquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario_borrador', to=settings.AUTH_USER_MODEL)),
                ('prev_paquete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.prevpaquete')),
            ],
        ),
    ]
