# Generated by Django 3.1.1 on 2020-10-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='fecha_respuesta',
            field=models.DateField(blank=True, verbose_name='Fecha de respuesta'),
        ),
    ]
