# Generated by Django 3.1.1 on 2020-11-16 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bandeja_es', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='document_version',
        ),
        migrations.AlterField(
            model_name='version',
            name='archivo',
            field=models.FileField(upload_to='proyecto/documentos/'),
        ),
        migrations.AlterField(
            model_name='version',
            name='comentario',
            field=models.FileField(upload_to='proyecto/comentarios/'),
        ),
        migrations.AlterField(
            model_name='version',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[(1, '-------'), (2, 'Aprobado con Comentarios'), (3, 'Rechazado'), (4, 'Eliminado'), (5, 'Aprobado'), (6, 'Valido para construcción'), (7, 'Aprobado (en numeracion)')], default=1),
        ),
        migrations.AlterField(
            model_name='version',
            name='estado_contratista',
            field=models.IntegerField(blank=True, choices=[(1, '-------'), (2, 'Para revisión'), (3, 'Para aprobación')], default=1),
        ),
        migrations.AlterField(
            model_name='version',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
    ]
