# Generated by Django 3.1.1 on 2020-11-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
    ]
