# Generated by Django 3.1.1 on 2020-12-11 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_carga', '0002_auto_20201211_0359'),
        ('bandeja_es', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borradorpaquete',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_borrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borradorpaquete',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario_borrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borradorpaquete',
            name='version',
            field=models.ManyToManyField(blank=True, through='bandeja_es.BorradorDocumento', to='bandeja_es.BorradorVersion'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='documento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[('', '---'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado (en numeracion)')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='estado_contratista',
            field=models.IntegerField(blank=True, choices=[('', '---'), (1, 'Para revisión'), (2, 'Para aprobación')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='prevversion',
            name='prev_estado_cliente',
            field=models.IntegerField(blank=True, choices=[('', '---'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado (en numeracion)')], default=1),
        ),
        migrations.AlterField(
            model_name='prevversion',
            name='prev_estado_contratista',
            field=models.IntegerField(blank=True, choices=[('', '---'), (1, 'Para revisión'), (2, 'Para aprobación')], default=1),
        ),
        migrations.AlterField(
            model_name='version',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[('', '---'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado (en numeracion)')], default=1),
        ),
        migrations.AlterField(
            model_name='version',
            name='estado_contratista',
            field=models.IntegerField(blank=True, choices=[('', '---'), (1, 'Para revisión'), (2, 'Para aprobación')], default=1),
        ),
    ]
