# Generated by Django 3.1.1 on 2020-11-10 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bandeja_es', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado')], default=1),
        ),
        migrations.AddField(
            model_name='version',
            name='estado_contratista',
            field=models.IntegerField(blank=True, choices=[(1, 'Para revisión'), (2, 'Para aprobación')], default=1),
        ),
        migrations.AddField(
            model_name='version',
            name='is_cliente_contratista',
            field=models.BooleanField(default=1, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='version',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AddField(
            model_name='version',
            name='revision',
            field=models.CharField(default='B', max_length=1, verbose_name='Emicion/Revision'),
        ),
    ]
