# Generated by Django 3.1.1 on 2021-03-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0002_auto_20210308_1241'),
        ('bandeja_es', '0002_auto_20210308_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevpaquete',
            name='proyecto',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='prev_paquete', to='panel_carga.proyecto'),
            preserve_default=False,
        ),
    ]
