# Generated by Django 3.1.1 on 2020-12-11 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_carga', '0002_auto_20201211_0359'),
        ('bandeja_es', '0002_auto_20201211_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borradorpaquete',
            name='asunto',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='borradorpaquete',
            name='descripcion',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='borradorpaquete',
            name='destinatario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_borrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borradorpaquete',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario_borrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borradorpaquete',
            name='version',
            field=models.ManyToManyField(blank=True, default=None, through='bandeja_es.BorradorDocumento', to='bandeja_es.BorradorVersion'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='archivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='proyecto/documentos/'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='comentario',
            field=models.FileField(blank=True, default=None, null=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='documento_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[('', '---'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado (en numeracion)')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='estado_contratista',
            field=models.IntegerField(blank=True, choices=[('', '---'), (1, 'Para revisión'), (2, 'Para aprobación')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='revision',
            field=models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='Revisión'),
        ),
    ]
