# Generated by Django 3.1.1 on 2020-11-18 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bandeja_es', '0002_auto_20201116_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='archivo',
            field=models.FileField(blank=True, upload_to='proyecto/documentos/'),
        ),
        migrations.AlterField(
            model_name='version',
            name='comentario',
            field=models.FileField(blank=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AlterField(
            model_name='version',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado (en numeracion)')], default=1),
        ),
        migrations.AlterField(
            model_name='version',
            name='estado_contratista',
            field=models.IntegerField(blank=True, choices=[(1, 'Para revisión'), (2, 'Para aprobación')], default=1),
        ),
        migrations.AlterField(
            model_name='version',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
    ]
