# Generated by Django 3.1.1 on 2021-01-28 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0003_auto_20210127_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borradorversion',
            name='documento_fk',
        ),
        migrations.RemoveField(
            model_name='borradorversion',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='borradorpaquete',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='borradorpaquete',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='borradorpaquete',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='borradorpaquete',
            name='version',
        ),
        migrations.AddField(
            model_name='borradorpaquete',
            name='prev_paquete',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.prevpaquete'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BorradorDocumento',
        ),
        migrations.DeleteModel(
            name='BorradorVersion',
        ),
    ]
