# Generated by Django 3.1.1 on 2021-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0003_prevpaquete_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[('', '------'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Válido para construcción'), (6, 'Mantener Revisión')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='estado_contratista',
            field=models.IntegerField(blank=True, choices=[('', '------'), (1, 'Para revisión'), (2, 'Para aprobación')], default=1, null=True),
        ),
    ]
