# Generated by Django 3.1.1 on 2020-11-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0003_auto_20201119_1703'),
        ('bandeja_es', '0003_auto_20201118_2243'),
    ]

    operations = [
    ]
