# Generated by Django 3.1.1 on 2021-03-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0004_auto_20210309_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prevversion',
            name='prev_comentario',
        ),
        migrations.RemoveField(
            model_name='version',
            name='comentario',
        ),
        migrations.AddField(
            model_name='paquete',
            name='codigo',
            field=models.CharField(default='0001', max_length=100, unique=True, verbose_name='Codigo del Proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='comentario',
            field=models.FileField(blank=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_comentario',
            field=models.FileField(blank=True, upload_to='proyecto/comentarios/'),
        ),
    ]
