# Generated by Django 3.1.1 on 2020-11-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0004_auto_20201112_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='status',
            field=models.CharField(blank=True, default='Para revision', max_length=10, verbose_name='Status'),
        ),
    ]
