# Generated by Django 3.1.1 on 2021-03-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0005_auto_20210325_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='comentario',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AlterField(
            model_name='prevpaquete',
            name='prev_comentario',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/comentarios/'),
        ),
    ]
