# Generated by Django 3.1.1 on 2020-11-25 20:48

import bandeja_es.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_carga', '0006_auto_20201118_2243'),
        ('bandeja_es', '0005_auto_20201119_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevPaquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('prev_fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('prev_asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('prev_descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('prev_status', models.BooleanField(blank=True, default=0, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='PrevVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Version')),
                ('prev_comentario', models.FileField(blank=True, upload_to='proyecto/comentarios/')),
                ('prev_archivo', models.FileField(blank=True, upload_to='proyecto/documentos/')),
                ('prev_revision', models.CharField(default='B', max_length=1, verbose_name='Emicion/Revision')),
                ('prev_estado_cliente', models.IntegerField(blank=True, choices=[(1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado (en numeracion)')], default=1)),
                ('prev_estado_contratista', models.IntegerField(blank=True, choices=[(1, 'Para revisión'), (2, 'Para aprobación')], default=1)),
                ('prev_valido', models.BooleanField(default=1, verbose_name='Valido')),
                ('prev_documento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento')),
                ('prev_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
                ('prev_paquete_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.prevpaquete', verbose_name=bandeja_es.models.Paquete)),
            ],
        ),
        migrations.CreateModel(
            name='PrevPaqueteDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('prev_documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento')),
                ('prev_paquete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.prevpaquete')),
            ],
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_documento',
            field=models.ManyToManyField(through='bandeja_es.PrevPaqueteDocumento', to='panel_carga.Documento'),
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevpropietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevdestinatario', to=settings.AUTH_USER_MODEL),
        ),
    ]
