# Generated by Django 3.1.1 on 2020-11-26 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0006_auto_20201118_2243'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bandeja_es', '0006_auto_20201125_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrador',
            name='asunto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='borrador',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_borrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrador',
            name='documento',
            field=models.ManyToManyField(blank=True, null=True, through='bandeja_es.BorradorDocumento', to='panel_carga.Documento'),
        ),
        migrations.AlterField(
            model_name='borrador',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='borrador',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='borrador',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario_borrador', to=settings.AUTH_USER_MODEL),
        ),
    ]
