# Generated by Django 3.1.1 on 2021-05-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0007_auto_20210502_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevversion',
            name='prev_archivo',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/documentos/'),
        ),
    ]
