# Generated by Django 3.1.1 on 2020-11-30 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bandeja_es', '0008_auto_20201126_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borradorversion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/documentos/'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='comentario',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado (en numeracion)')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='estado_contratista',
            field=models.IntegerField(blank=True, choices=[(1, 'Para revisión'), (2, 'Para aprobación')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Version'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='paquete_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.borrador', verbose_name='Paquete Borrador'),
        ),
        migrations.AlterField(
            model_name='borradorversion',
            name='revision',
            field=models.CharField(blank=True, default='B', max_length=1, null=True, verbose_name='Emicion/Revision'),
        ),
        migrations.AlterField(
            model_name='prevversion',
            name='prev_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='prevversion',
            name='prev_paquete_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandeja_es.prevpaquete', verbose_name='Paquete Preview'),
        ),
        migrations.AlterField(
            model_name='version',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
    ]
