# Generated by Django 3.1.1 on 2020-12-02 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bandeja_es', '0010_auto_20201202_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrador',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='borrador',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_borrador', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='borrador',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_borrador', to='auth.user'),
        ),
    ]
