# Generated by Django 3.1.1 on 2021-10-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0010_auto_20211005_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevpaquete',
            name='prev_asunto',
            field=models.CharField(max_length=300, verbose_name='Asunto'),
        ),
    ]
