# Generated by Django 3.1.1 on 2021-10-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0011_auto_20211005_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='tipo',
            field=models.IntegerField(choices=[('', '------'), (1, 'Información Técnica'), (2, 'Informativo')], default=1, verbose_name='Tipo de Paquete'),
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='tipo',
            field=models.IntegerField(choices=[('', '------'), (1, 'Información Técnica'), (2, 'Informativo')], default=1, verbose_name='Tipo de Paquete'),
        ),
    ]
