# Generated by Django 3.1.1 on 2021-10-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0012_auto_20211006_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevversion',
            name='prev_estado_cliente',
            field=models.IntegerField(blank=True, choices=[('', '------'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Anulado'), (4, 'Aprobado'), (5, 'Válido para construcción'), (6, 'Mantener Revisión'), (7, 'Excepción')], null=True),
        ),
        migrations.AlterField(
            model_name='prevversion',
            name='prev_estado_contratista',
            field=models.IntegerField(blank=True, choices=[('', '------'), (1, 'Para revisión'), (2, 'Para aprobación'), (3, 'As Built')], null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[('', '------'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Anulado'), (4, 'Aprobado'), (5, 'Válido para construcción'), (6, 'Mantener Revisión'), (7, 'Excepción')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='estado_contratista',
            field=models.IntegerField(blank=True, choices=[('', '------'), (1, 'Para revisión'), (2, 'Para aprobación'), (3, 'As Built')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='VersionAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proyecto/documentos/adjuntos', verbose_name='Archivo')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='bandeja_es.version', verbose_name='Version')),
            ],
        ),
        migrations.CreateModel(
            name='PrevVersionAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proyecto/documentos/adjuntos', verbose_name='Archivo')),
                ('prev_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='bandeja_es.prevversion', verbose_name='Prev Version')),
            ],
        ),
    ]
