# Generated by Django 3.1.1 on 2021-10-19 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0013_auto_20211019_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proyecto/documentos/adjuntos', verbose_name='Archivo')),
                ('Paquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='bandeja_es.version', verbose_name='Paquete')),
            ],
        ),
        migrations.CreateModel(
            name='PrevPaqueteAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proyecto/documentos/adjuntos', verbose_name='Archivo')),
                ('prev_paquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='bandeja_es.prevpaquete', verbose_name='Prev Paquete')),
            ],
        ),
        migrations.RemoveField(
            model_name='versionattachment',
            name='version',
        ),
        migrations.DeleteModel(
            name='PrevVersionAttachment',
        ),
        migrations.DeleteModel(
            name='VersionAttachment',
        ),
    ]
