# Generated by Django 3.1.1 on 2021-10-19 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0014_auto_20211019_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevpaqueteattachment',
            name='prev_paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bandeja_es.prevpaquete', verbose_name='Prev Paquete'),
        ),
    ]
