# Generated by Django 3.1.1 on 2021-10-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0015_auto_20211019_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paqueteattachment',
            name='Paquete',
        ),
        migrations.AddField(
            model_name='paqueteattachment',
            name='paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='bandeja_es.paquete', verbose_name='Paquete'),
        ),
    ]
