# Generated by Django 3.1.1 on 2021-10-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0016_auto_20211019_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='comentario',
            new_name='comentario1',
        ),
        migrations.RenameField(
            model_name='prevpaquete',
            old_name='prev_comentario',
            new_name='prev_comentario1',
        ),
        migrations.AddField(
            model_name='paquete',
            name='comentario2',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='comentario3',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='comentario4',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_comentario2',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_comentario3',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/comentarios/'),
        ),
        migrations.AddField(
            model_name='prevpaquete',
            name='prev_comentario4',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/comentarios/'),
        ),
    ]
