# Generated by Django 3.1.1 on 2021-11-18 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0018_auto_20211020_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='version',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Versión'),
        ),
    ]
