# Generated by Django 3.1.1 on 2022-02-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0021_auto_20220211_1423'),
        ('bandeja_es', '0021_auto_20220211_2239'),
    ]

    operations = [
    ]
