# Generated by Django 3.1.1 on 2022-02-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0022_merge_20220212_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevversion',
            name='prev_revision',
            field=models.IntegerField(blank=True, choices=[('', '------'), (1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, '0'), (7, '1'), (8, '2'), (9, '3'), (10, '4'), (11, '5')], verbose_name='Revisión'),
        ),
        migrations.AlterField(
            model_name='version',
            name='revision',
            field=models.IntegerField(blank=True, choices=[('', '------'), (1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, '0'), (7, '1'), (8, '2'), (9, '3'), (10, '4'), (11, '5')], verbose_name='Revisión'),
        ),
    ]
