# Generated by Django 3.1.1 on 2020-10-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel_carga', '0009_auto_20201021_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del paquete')),
                ('fecha', models.DateField(verbose_name='Fecha de respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento')),
                ('paquete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paquete')),
            ],
        ),
        migrations.AddField(
            model_name='paquete',
            name='documento',
            field=models.ManyToManyField(through='dashboard.PaqueteDocumento', to='panel_carga.Documento'),
        ),
    ]
