# Generated by Django 3.1.1 on 2022-03-15 23:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0019_documento_valor_monetario'),
        ('analitica', '0002_curvasbasehh'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurvasBaseValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('datos_lista', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), size=None)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_carga.proyecto', verbose_name='Proyecto')),
            ],
        ),
    ]
