# Generated by Django 3.1.1 on 2020-11-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_Emision_0',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Fecha inicio emisión'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_Emision_B',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Fecha inicio emisión'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de Termino'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='fecha_estimada',
            field=models.DateTimeField(default='2021-01-01', verbose_name='Fecha rev 0'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_version', models.CharField(max_length=5, verbose_name='Version documento')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Version')),
                ('comentario', models.FileField(blank=True, upload_to='proyecto/comentarios/')),
                ('archivo', models.FileField(blank=True, upload_to='proyecto/documentos/')),
                ('documento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento')),
            ],
        ),
    ]
