# Generated by Django 3.1.1 on 2020-10-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15, unique=True, verbose_name='Tipo Documento')),
            ],
        ),
        migrations.RemoveField(
            model_name='documento',
            name='emision',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='revision',
            name='documento',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento'),
        ),
        migrations.AddField(
            model_name='revision',
            name='fecha_estimada',
            field=models.DateField(default='2021-01-01', verbose_name='Fecha rev 0'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='documento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.tipo_documento'),
        ),
    ]
