# Generated by Django 3.1.1 on 2020-10-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_doc',
            field=models.CharField(default=None, max_length=50, verbose_name='Tipo Documento'),
            preserve_default=False,
        ),
    ]
