# Generated by Django 3.1.1 on 2020-10-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='emision',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.revision'),
        ),
    ]
