# Generated by Django 3.1.1 on 2020-10-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0002_auto_20201028_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Fecha_Emision_0',
            field=models.DateField(default=None, verbose_name='Fecha inicio emisión en 0'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Fecha_Emision_B',
            field=models.DateField(default=None, verbose_name='Fecha inicio emisión en B'),
        ),
    ]
