# Generated by Django 3.1.1 on 2020-10-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0002_auto_20201027_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='num_documento',
            new_name='Codigo_documento',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='especialidad',
            new_name='Especialidad',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='proyecto',
            new_name='Proyecto',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='tipo_doc',
            new_name='Tipo_de_Documento',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha_fin_Emision',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha_inicio_Emision',
        ),
        migrations.AddField(
            model_name='documento',
            name='Fecha_Inicio_Emision_0',
            field=models.DateField(blank=True, default=None, verbose_name='Fecha inicio emisión en 0'),
        ),
        migrations.AddField(
            model_name='documento',
            name='Fecha_inicio_Emision_B',
            field=models.DateField(blank=True, default=None, verbose_name='Fecha inicio emisión en B'),
        ),
        migrations.AddField(
            model_name='documento',
            name='Numero_Doc_Interno',
            field=models.CharField(default=None, max_length=100, verbose_name='Numero Documento Interno'),
            preserve_default=False,
        ),
    ]
