# Generated by Django 3.1.1 on 2020-10-19 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0002_auto_20201019_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_carga.tipo_documento'),
        ),
    ]
