# Generated by Django 3.1.1 on 2021-03-25 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_carga', '0002_auto_20210308_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='participantes',
            field=models.ManyToManyField(related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='umbral_desviacion_porcentual',
            field=models.FloatField(default=0, verbose_name='Umbral para Dviación Porcentual del Proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='umbral_documento_aprobado',
            field=models.IntegerField(default=0, verbose_name='Umbral para Documentos Aprobados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='umbral_documento_atrasado',
            field=models.IntegerField(default=0, verbose_name='Umbral para Documentos Atrasados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='umbral_revision_documento',
            field=models.IntegerField(default=0, verbose_name='Umbral para Revisiones Atrasadas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
    ]
