# Generated by Django 3.1.1 on 2020-10-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0002_auto_20200930_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(verbose_name='estado')),
                ('fecha_inicio', models.DateTimeField(editable=False, verbose_name='Fecha_de_Inicio')),
                ('fecha_temrino', models.DateTimeField(blank=True, verbose_name='Fecha_de_Termino')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(default=0, max_length=50, verbose_name='tipo_documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre_del_Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='num_documento',
            field=models.CharField(max_length=100, verbose_name='Número_de_Documento'),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo_Revision')),
                ('emitida_para', models.TextField(verbose_name='Emitida_para')),
                ('fecha', models.DateTimeField(editable=False, verbose_name='Fecha')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_carga.estado')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='emision',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.revision'),
            preserve_default=False,
        ),
    ]
