# Generated by Django 3.1.1 on 2020-11-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0002_auto_20201104_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
