# Generated by Django 3.1.1 on 2021-01-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0002_auto_20201219_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_Emision_0',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Fecha inicio emisión 0'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_Emision_B',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Fecha inicio emisión B'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='estado_cliente',
            field=models.IntegerField(choices=[('', '------'), (1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Válido para construcción'), (6, 'Mantener Revisión')], default=1),
        ),
        migrations.AlterField(
            model_name='revision',
            name='estado_contratista',
            field=models.IntegerField(choices=[('', '------'), (1, 'Para revisión'), (2, 'Para aprobación')], default=1),
        ),
        migrations.AlterField(
            model_name='revision',
            name='tipo',
            field=models.IntegerField(choices=[('', '------'), (1, 'Revision B'), (2, 'Revision C'), (3, 'Revision D'), (4, 'Revision E'), (5, 'Revision 0'), (6, 'Revision 1'), (7, 'Revision 2'), (8, 'Revision 3'), (9, 'Revision 4'), (10, 'Revision 5')], verbose_name='Tipo Revision'),
        ),
    ]
