# Generated by Django 3.1.1 on 2020-10-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0002_auto_20201013_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Documento'), (2, 'Plano')], default=1),
        ),
    ]
