# Generated by Django 3.1.1 on 2020-10-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0003_auto_20201028_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Fecha_Inicio_Emision_0',
            new_name='Fecha_Emision_0',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='Fecha_inicio_Emision_B',
            new_name='Fecha_Emision_B',
        ),
        migrations.AlterField(
            model_name='documento',
            name='Numero_Doc_Interno',
            field=models.CharField(default=None, max_length=100, verbose_name='Numero Documento Interno'),
        ),
    ]
