# Generated by Django 3.1.1 on 2021-03-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0003_auto_20210325_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='emitida_para',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='estado_cliente',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='estado_contratista',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='fecha_estimada',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='owner',
        ),
        migrations.AddField(
            model_name='revision',
            name='porcentaje',
            field=models.FloatField(default=0, verbose_name='Porcentaje de Avance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revision',
            name='tipo',
            field=models.CharField(max_length=1, verbose_name='Letra o Número'),
        ),
    ]
