# Generated by Django 3.1.1 on 2020-10-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0003_auto_20201019_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(default='PDF', max_length=15, verbose_name='Tipo Documento'),
        ),
    ]
