# Generated by Django 3.1.1 on 2020-11-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0003_delete_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='estado_cliente',
            field=models.IntegerField(choices=[(1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado (en numeracion)')], default=1),
        ),
    ]
