# Generated by Django 3.1.1 on 2021-01-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0003_auto_20210127_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(default='--', max_length=100, unique=True, verbose_name='Codigo del Proyecto'),
            preserve_default=False,
        ),
    ]
