# Generated by Django 3.1.1 on 2020-11-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0004_auto_20201112_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='estado_cliente',
            field=models.IntegerField(choices=[(1, '-------'), (2, 'Aprobado con Comentarios'), (3, 'Rechazado'), (4, 'Eliminado'), (5, 'Aprobado'), (6, 'Valido para construcción'), (7, 'Aprobado (en numeracion)')], default=1),
        ),
        migrations.AlterField(
            model_name='revision',
            name='estado_contratista',
            field=models.IntegerField(choices=[(1, '-------'), (2, 'Para revisión'), (3, 'Para aprobación')], default=1),
        ),
    ]
