# Generated by Django 3.1.1 on 2020-10-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0004_auto_20201002_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='num_documento',
            field=models.CharField(max_length=100, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Típo de Documento'),
        ),
    ]
