# Generated by Django 3.1.1 on 2020-10-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0004_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='num_documento',
            field=models.CharField(max_length=100, verbose_name='Codigo Documento'),
        ),
    ]
