# Generated by Django 3.1.1 on 2021-05-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0004_auto_20210326_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='Numero_documento_interno',
        ),
    ]
