# Generated by Django 3.1.1 on 2020-10-19 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0005_auto_20201019_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.tipo_documento'),
        ),
    ]
