# Generated by Django 3.1.1 on 2020-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0005_auto_20201116_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='estado_cliente',
            field=models.IntegerField(choices=[(1, 'Aprobado con Comentarios'), (2, 'Rechazado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Valido para construcción'), (6, 'Aprobado (en numeracion)')], default=1),
        ),
        migrations.AlterField(
            model_name='revision',
            name='estado_contratista',
            field=models.IntegerField(choices=[(1, 'Para revisión'), (2, 'Para aprobación')], default=1),
        ),
    ]
