# Generated by Django 3.1.1 on 2021-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0006_documento_numero_documento_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Numero_documento_interno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero documento Interno'),
        ),
    ]
