# Generated by Django 3.1.1 on 2020-10-07 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0007_auto_20201006_2308'),
    ]

    operations = [

        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_temrino',
            new_name='fecha_termino',
        ),
        migrations.AlterField(
            model_name='documento',
            name='emision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.revision'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='num_documento',
            field=models.CharField(max_length=100, verbose_name='Codigo Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Documento'), (2, 'Plano')], default=1),
        ),
        migrations.AlterField(
            model_name='revision',
            name='emitida_para',
            field=models.TextField(verbose_name='Emitida para'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Revision B'), (2, 'Revision C'), (3, 'Revision D'), (4, 'Revision E'), (5, 'Revision F'), (6, 'Revision G'), (7, 'Revision H'), (8, 'Revision I'), (9, 'Revision J'), (10, 'Revision K'), (11, 'Revision L'), (12, 'Revision M'), (13, 'Revision N'), (14, 'Revision O'), (15, 'Revision P'), (16, 'Revision Q'), (17, 'Revision R'), (18, 'Revision S'), (19, 'Revision T'), (20, 'Revision U'), (21, 'Revision V'), (22, 'Revision W'), (23, 'Revision X'), (24, 'Revision Y'), (25, 'Revision Z'), (26, 'Revision 0'), (27, 'Revision 1'), (28, 'Revision 2'), (29, 'Revision 3'), (30, 'Revision 4'), (31, 'Revision 5'), (32, 'Revision 6'), (33, 'Revision 7'), (34, 'Revision 8'), (35, 'Revision 9')], default=1, verbose_name='Tipo Revision'),
        ),
    ]
