# Generated by Django 3.1.1 on 2020-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0007_auto_20201021_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='documento',
            field=models.ManyToManyField(through='panel_carga.PaqueteDocumento', to='panel_carga.Documento'),
        ),
    ]
