# Generated by Django 3.1.1 on 2021-07-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0007_auto_20210526_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='umbral_desviacion_porcentual',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='umbral_documento_aprobado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='umbral_documento_atrasado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='umbral_revision_documento',
        ),
    ]
