# Generated by Django 3.1.1 on 2020-10-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0008_auto_20201007_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, default=None, upload_to='proyecto/documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='emision',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.revision'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='proyecto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.proyecto'),
            preserve_default=False,
        ),
    ]
