# Generated by Django 3.1.1 on 2020-10-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0009_auto_20201007_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(null=True, upload_to='proyecto/documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='emision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.revision'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_carga.proyecto'),
        ),
    ]
