# Generated by Django 3.1.1 on 2021-08-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0009_auto_20210722_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='rev_letra',
            field=models.FloatField(default=0.0, max_length=3, verbose_name='Porcentaje de Avance para Rev en letras'),
        ),
    ]
