# Generated by Django 3.1.1 on 2021-08-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0010_proyecto_rev_letra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='rev_letra',
            field=models.FloatField(default=70.0, max_length=3, verbose_name='Porcentaje de Avance para Rev en letras'),
        ),
    ]
