# Generated by Django 3.1.1 on 2022-01-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0012_auto_20210907_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='hh_emision_0',
            field=models.IntegerField(default=0, verbose_name='HH Emisión 0'),
        ),
        migrations.AddField(
            model_name='documento',
            name='hh_emision_B',
            field=models.IntegerField(default=0, verbose_name='HH Emisión B'),
        ),
    ]
