# Generated by Django 3.1.1 on 2022-01-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0013_auto_20220111_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='hh_emision_0',
            field=models.FloatField(default=0, verbose_name='HH Emisión 0'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='hh_emision_B',
            field=models.FloatField(default=0, verbose_name='HH Emisión B'),
        ),
    ]
