# Generated by Django 3.1.1 on 2022-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0015_auto_20220114_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='hh_emision_B',
            field=models.FloatField(default=0.0, max_length=3, verbose_name='HH Emisión B'),
        ),
    ]
