# Generated by Django 3.1.1 on 2022-01-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0017_remove_documento_hh_emision_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipo_porcentaje_avance',
            field=models.IntegerField(choices=[(0, 'Porcentaje de Avance en Tiempo'), (1, 'Porcentaje de Avance en Unidades')], default=0, verbose_name='Tipo de Porcentaje Avance'),
        ),
    ]
