# Generated by Django 3.1.1 on 2022-03-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0018_proyecto_tipo_porcentaje_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='valor_monetario',
            field=models.IntegerField(default=0, max_length=99999999999, verbose_name='HH Emisión 0'),
        ),
    ]
