# Generated by Django 3.1.1 on 2022-03-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0019_documento_valor_monetario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='valor_monetario',
            field=models.IntegerField(default=0, verbose_name='HH Emisión 0'),
        ),
    ]
