# Generated by Django 3.1.1 on 2021-06-15 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0003_auto_20210614_2331'),
        ('panel_carga', '0007_auto_20210526_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('contidad_hh', models.IntegerField(max_length=100, verbose_name='Cantidad Horas Hombre')),
                ('estado', models.BooleanField(blank=True, default=0, verbose_name='Estado')),
                ('plazo', models.DateField(verbose_name='Fecha de Plazo')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_document', to='panel_carga.documento', verbose_name='Documento')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taks_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
                ('restricciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_restrictions', to='configuracion.restricciones', verbose_name='Restricciones')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('contidad_hh', models.IntegerField(max_length=100, verbose_name='Cantidad Horas Hombre')),
                ('comentarios', models.TextField(verbose_name='Comentarios')),
                ('not_done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_excuse', to='configuracion.causasnocumplimiento', verbose_name='Causa no Cumplimiento')),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_answer', to='status_encargado.tarea', verbose_name='Tarea')),
            ],
        ),
    ]
