# Generated by Django 3.1.1 on 2021-06-21 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20210620_1933'),
        ('status_encargado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='contidad_hh',
            field=models.IntegerField(verbose_name='Cantidad Horas Hombre'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='not_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_excuse', to='configuracion.causasnocumplimiento', verbose_name='Causa no Cumplimiento'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='contidad_hh',
            field=models.IntegerField(verbose_name='Cantidad Horas Hombre'),
        ),
    ]
