# Generated by Django 3.1.1 on 2021-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_encargado', '0004_auto_20210624_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='respuestas/documentos/', verbose_name='Archivo'),
        ),
    ]
