# Generated by Django 3.1.1 on 2021-07-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_encargado', '0005_auto_20210625_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='respuestas/documentos/', verbose_name='Archivo'),
        ),
    ]
