# Generated by Django 3.1.1 on 2021-07-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_encargado', '0006_tarea_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='tareas/documentos/', verbose_name='Archivo'),
        ),
    ]
