# Generated by Django 3.1.1 on 2021-09-28 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_auto_20210823_2151'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status_encargado', '0007_auto_20210706_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='not_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_excuse', to='configuracion.causasnocumplimiento', verbose_name='Causa no Cumplimiento'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_answer', to='status_encargado.tarea', verbose_name='Tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='encargado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='taks_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='restricciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_restrictions', to='configuracion.restricciones', verbose_name='Restricciones'),
        ),
    ]
