# Generated by Django 3.1.1 on 2021-09-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_encargado', '0008_auto_20210928_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Sin Evaluación'), (2, 'Aprobado'), (3, 'Rechazado')], default=1, verbose_name='tipo de estado'),
        ),
    ]
