# Generated by Django 3.1.1 on 2021-10-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_encargado', '0009_respuesta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='motivo',
            field=models.TextField(blank=True, default='', verbose_name='Evaluación'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='comentarios',
            field=models.TextField(default='', verbose_name='Comentarios'),
        ),
    ]
