# Generated by Django 3.1.1 on 2021-11-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status_encargado', '0011_auto_20211116_1834'),
        ('status_encargado', '0011_auto_20211115_1933'),
    ]

    operations = [
    ]
