# Generated by Django 3.1.1 on 2021-01-29 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/foto/%Y/%m/%d')),
                ('rol_usuario', models.IntegerField(choices=[('', '-----'), (1, 'Administrador'), (2, 'Revisor'), (3, 'Vizualizador'), (4, 'Administrador (invitado)')], verbose_name='Rol de Usuario')),
                ('empresa', models.CharField(max_length=60, verbose_name='Empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
