# Generated by Django 3.1.1 on 2020-12-16 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/foto/%Y/%m/%d')),
                ('administrador', models.BooleanField(default=0, verbose_name='Administrador')),
                ('revisor', models.BooleanField(default=0, verbose_name='Revisor')),
                ('visualizador', models.BooleanField(default=0, verbose_name='Visualizador')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
