# Generated by Django 3.1.1 on 2020-12-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='revisor',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='visualizador',
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol_usuario',
            field=models.IntegerField(choices=[('', '-----'), (1, 'Administrador'), (2, 'Revisor'), (3, 'Vizualizador')], default=0, verbose_name='Rol de Usuario'),
            preserve_default=False,
        ),
    ]
