# Generated by Django 3.1.1 on 2021-01-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20201228_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.CharField(default='Sin Empresa', max_length=60, verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
