# Generated by Django 3.1.1 on 2021-01-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_perfil_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol_usuario',
            field=models.IntegerField(choices=[('', '-----'), (1, 'Administrador'), (2, 'Revisor'), (3, 'Vizualizador'), (4, 'Administrador (invitado)')], verbose_name='Rol de Usuario'),
        ),
    ]
