# Generated by Django 3.1.1 on 2021-07-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_carga', '0007_auto_20210526_1529'),
        ('notifications', '0001_initial'),
        ('configuracion', '0004_auto_20210620_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialUmbrales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateField(verbose_name='Ultima Revisión')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hu_proyecto', to='panel_carga.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Umbral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionHU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos', models.ManyToManyField(related_name='hu_documentos', to='panel_carga.Documento', verbose_name='Listado de Documentos')),
                ('h_umbral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_umbral', to='configuracion.historialumbrales')),
                ('notificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hu_notificacion', to='notifications.notificacion')),
            ],
        ),
        migrations.AddField(
            model_name='historialumbrales',
            name='umbral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umbral', to='configuracion.umbral'),
        ),
    ]
