# Generated by Django 3.1.1 on 2021-07-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_auto_20210713_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cargo_empresa',
            field=models.CharField(default='', max_length=128, verbose_name='Cargo en Empresa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.CharField(default='', max_length=64, verbose_name='Empresa'),
        ),
    ]
