# Generated by Django 3.1.1 on 2021-07-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_auto_20210721_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialumbrales',
            name='tiempo_control',
            field=models.IntegerField(default=0, verbose_name='Días de notificación'),
        ),
        migrations.AddField(
            model_name='historialumbrales',
            name='variable_atraso',
            field=models.IntegerField(default=0, verbose_name='Días de atraso'),
        ),
        migrations.AddField(
            model_name='umbral',
            name='descripcion',
            field=models.CharField(default='', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='umbral',
            name='nombre',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
