# Generated by Django 3.1.1 on 2021-08-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_auto_20210722_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialumbrales',
            name='last_checked',
            field=models.DateTimeField(verbose_name='Ultima Revisión'),
        ),
    ]
