# Generated by Django 3.1.1 on 2021-08-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja_es', '0008_auto_20210502_2325'),
        ('configuracion', '0008_auto_20210803_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionhu',
            name='versiones',
            field=models.ManyToManyField(related_name='hu_versiones', to='bandeja_es.Version', verbose_name='Listado de Versiones'),
        ),
    ]
