# Generated by Django 3.1.1 on 2021-08-19 02:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_notificacionhu_versiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionhu',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacionhu',
            name='porcentaje_atraso',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True, verbose_name='porcentaje de atraso'), null=True, size=None),
        ),
    ]
