# Generated by Django 3.1.1 on 2021-08-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_auto_20210823_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialumbrales',
            name='cliente_tiempo_control',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cliente Días de notificación'),
        ),
        migrations.AlterField(
            model_name='historialumbrales',
            name='cliente_variable_atraso',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cliente Días de atraso'),
        ),
        migrations.AlterField(
            model_name='historialumbrales',
            name='contratista_tiempo_control',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Contratista Días de notificación'),
        ),
        migrations.AlterField(
            model_name='historialumbrales',
            name='contratista_variable_atraso',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Contratista Días de atraso'),
        ),
    ]
